// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPHValueChange();
void onTdsValueChange();
void onLocationChange();
void onValveStateChange();

float pHValue;
float tdsValue;
CloudLocation location;
bool valveState;

void initProperties(){

  ArduinoCloud.addProperty(pHValue, READWRITE, 5 * SECONDS, onPHValueChange);
  ArduinoCloud.addProperty(tdsValue, READWRITE, 5 * SECONDS, onTdsValueChange);
  ArduinoCloud.addProperty(location, READWRITE, 5 * SECONDS, onLocationChange);
  ArduinoCloud.addProperty(valveState, READWRITE, ON_CHANGE, onValveStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
